import type { Metadata } from "next";
import LoginPage from "./page";
import "../globals.css";
import "@copilotkit/react-ui/styles.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        {
          <LoginPage />

          /*  */
        }
        <Toaster />
      </body>
    </html>
  );
}
